/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsCreateRouteImport } from './routes/sessions_.create'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions_.$sessionId'
import { Route as ProfileEditRouteImport } from './routes/profile_.edit'

const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsCreateRoute = SessionsCreateRouteImport.update({
  id: '/sessions_/create',
  path: '/sessions/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions_/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile_/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/discover': typeof DiscoverRoute
  '/profile': typeof ProfileRoute
  '/proposals': typeof ProposalsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/create': typeof SessionsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/discover': typeof DiscoverRoute
  '/profile': typeof ProfileRoute
  '/proposals': typeof ProposalsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/create': typeof SessionsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/discover': typeof DiscoverRoute
  '/profile': typeof ProfileRoute
  '/proposals': typeof ProposalsRoute
  '/profile_/edit': typeof ProfileEditRoute
  '/sessions_/$sessionId': typeof SessionsSessionIdRoute
  '/sessions_/create': typeof SessionsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/discover'
    | '/profile'
    | '/proposals'
    | '/profile/edit'
    | '/sessions/$sessionId'
    | '/sessions/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/discover'
    | '/profile'
    | '/proposals'
    | '/profile/edit'
    | '/sessions/$sessionId'
    | '/sessions/create'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/discover'
    | '/profile'
    | '/proposals'
    | '/profile_/edit'
    | '/sessions_/$sessionId'
    | '/sessions_/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DiscoverRoute: typeof DiscoverRoute
  ProfileRoute: typeof ProfileRoute
  ProposalsRoute: typeof ProposalsRoute
  ProfileEditRoute: typeof ProfileEditRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsCreateRoute: typeof SessionsCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions_/create': {
      id: '/sessions_/create'
      path: '/sessions/create'
      fullPath: '/sessions/create'
      preLoaderRoute: typeof SessionsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions_/$sessionId': {
      id: '/sessions_/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/edit': {
      id: '/profile_/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DiscoverRoute: DiscoverRoute,
  ProfileRoute: ProfileRoute,
  ProposalsRoute: ProposalsRoute,
  ProfileEditRoute: ProfileEditRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsCreateRoute: SessionsCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
